#!/bin/bash
#SBATCH --nodes=1             # Number of nodes 
#SBATCH -A lzc@a100
#SBATCH -C a100
#SBATCH --gres=gpu:4         # Allocate 4 GPUs per node
#SBATCH --partition=gpu_p5
#SBATCH --job-name=CellPose               # Jobname 
#SBATCH --cpus-per-task=40
#SBATCH --output=cell.o%j            # Output file 
#SBATCH --error=cell.o%j            # Error file 
#SBATCH --time=20:00:00       # Expected runtime HH:MM:SS (max 100h)
module purge # purging modules inherited by default

module load anaconda-py3/2020.11
#conda init bash # deactivating environments inherited by default
conda deactivate
conda activate /gpfswork/rech/lzc/uzj81mi/kapoorlabsenv
set -x # activating echo of
export XLA_FLAGS=--xla_gpu_cuda_data_dir=/gpfswork/rech/lzc/uzj81mi/kapoorlabsenv/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/gpfswork/rech/lzc/uzj81mi/kapoorlabsenv/lib/
python  /gpfswork/rech/jsy/uzj81mi/MTVKW/00_train_cellpose_3D.py


