#!/bin/bash
#SBATCH --nodes=1            
#SBATCH -A jsy@a100
#SBATCH --gres=gpu:1
#SBATCH -C a100
#SBATCH --partition=gpu_p5
#SBATCH --job-name=incetion             
#SBATCH --cpus-per-task=40
#SBATCH --output=cell.o%j           
#SBATCH --error=cell.o%j           
#SBATCH --time=20:00:00       
module purge 

module load anaconda-py3/2020.11

conda deactivate
conda activate capedenv
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/linkhome/rech/gengoq01/uzj81mi/.conda/envs/capedenv/lib/
export XLA_FLAGS=--xla_gpu_cuda_data_dir=/linkhome/rech/gengoq01/uzj81mi/.conda/envs/capedenv/	

python  /gpfswork/rech/jsy/uzj81mi/CopenhagenWorkflow/train_gbr_neural_net_morpho.py


