#!/bin/bash
#SBATCH --nodes=1             # Number of nodes
#SBATCH -A lzc@v100
##SBATCH -C a100
#SBATCH --gres=gpu:1         # Allocate 4 GPUs per node
#SBATCH --partition=gpu_p2
##SBATCH --qos=qos_gpu-t4
#SBATCH --job-name=ONEAT               # Jobname
#SBATCH --cpus-per-task=40
#SBATCH --output=oneat.o%j            # Output file
#SBATCH --error=oneat.o%j            # Error file
#SBATCH --time=20:00:00       # Expected runtime HH:MM:SS (max 100h)
module purge # purging modules inherited by default

module load anaconda-py3/2020.11
#conda init bash # deactivating environments inherited by default
conda deactivate
conda activate kapoorlabsenv
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/
export XLA_FLAGS=--xla_gpu_cuda_data_dir=$CONDA_PREFIX
mkdir -p $CONDA_PREFIX/lib/nvvm/libdevice/
cp -p $CONDA_PREFIX/lib/libdevice.10.bc $CONDA_PREFIX/lib/nvvm/libdevice/
module load cudnn/8.7.0.84-cuda
python  /gpfswork/rech/jsy/uzj81mi/MTVKW/02_oneat_nuclei.py                                                          
