#!/bin/bash
#SBATCH --nodes=1            
#SBATCH -A jsy@a100
#SBATCH -C a100
#SBATCH --gres=gpu:1        
#SBATCH --partition=gpu_p5
#SBATCH --job-name=OneMembrane            
#SBATCH --cpus-per-task=20
#SBATCH --output=one.o%j           
#SBATCH --error=one.o%j           
#SBATCH --time=20:00:00      
module purge 

module load anaconda-py3/2020.11
conda deactivate
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/
export XLA_FLAGS=--xla_gpu_cuda_data_dir=$CONDA_PREFIX
mkdir -p $CONDA_PREFIX/lib/nvvm/libdevice/
cp -p $CONDA_PREFIX/lib/libdevice.10.bc $CONDA_PREFIX/lib/nvvm/libdevice/
module load cuda/11.8.0
python  /gpfswork/rech/jsy/uzj81mi/MTVKW/01_vollcellpose_membrane_segmentation.py                                                             
