#!/bin/bash
#SBATCH --nodes=1            
#SBATCH -A lzc@v100
#SBATCH --job-name=Zero             
#SBATCH --cpus-per-task=40
#SBATCH --output=zero.o%j           
#SBATCH --error=zero.o%j           
#SBATCH --time=20:00:00      
module purge 
module load anaconda-py3/2020.11
conda deactivate
conda activate kapoorlabsenv
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/
export XLA_FLAGS=--xla_gpu_cuda_data_dir=$CONDA_PREFIX
mkdir -p $CONDA_PREFIX/lib/nvvm/libdevice/
cp -p $CONDA_PREFIX/lib/libdevice.10.bc $CONDA_PREFIX/lib/nvvm/libdevice/
module load cudnn/8.7.0.84-cuda
python  /gpfswork/rech/jsy/uzj81mi/MTVKW/00_create_nuclei_membrane_splits.py  