#!/bin/bash
#SBATCH --nodes=1             # Number of nodes 
#SBATCH -A jsy@a100
##SBATCH -C a100
#SBATCH --partition=prepost
##SBATCH --gres=gpu:1
#SBATCH --job-name=Track               # Jobname 
#SBATCH --cpus-per-task=20
#SBATCH --output=track.o%j            # Output file 
#SBATCH --error=track.o%j            # Error file 
#SBATCH --time=20:00:00       # Expected runtime HH:MM:SS (max 100h)
module purge # purging modules inherited by default

module load anaconda-py3/2020.11
#conda init bash # deactivating environments inherited by default
conda deactivate
conda activate kapoorlabsenv
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/linkhome/rech/gengoq01/uzj81mi/.conda/envs/kapoorlabsenv/lib/
export XLA_FLAGS=--xla_gpu_cuda_data_dir=/linkhome/rech/gengoq01/uzj81mi/.conda/envs/kapoorlabsenv/
module load cuda/11.8.0

python  /gpfswork/rech/jsy/uzj81mi/MTVKW/05_master_tracking.py
