name: deploy-book

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"   # note the quotes!

      - name: Install dependencies
        run: |
          pip install -U jupyter-book ghp-import

      - name: Build book
        run: jupyter-book build docs  # or "." if your book root is repo root

      - name: Deploy to GitHub Pages
        run: ghp-import -n -p -f docs/_build/html   # adjust path if book root differs